#! /bin/sh
#$ -S /bin/sh

#$ -pe smp 10
#$ -cwd
#$ -V

#### Jobdescription at qstat
#$ -N run_deseq_volcano_names
#### Error Outputfile
#$ -e ./LOGS/$JOB_NAME-$JOB_ID.err
#$ -o ./LOGS/$JOB_NAME-$JOB_ID.log

#### Resubmit
#$ -r y

hostname

Rscript runDESeq2_ICBI_volcano_names.R /data/scratch/kvalem/projects/2023/pseudomonas_aeruginosa/tables/samplesheet_deseq_batch_effect.csv  /data/scratch/kvalem/projects/2023/pseudomonas_aeruginosa/tables/salmon.merged.gene_counts.tsv --result_dir=/data/projects/2023/Pseudomonas_aeruginosa/20_deseq2icbi/06_deseq2_batch_effect_volcano_names --genes_of_interest=/data/projects/2023/Pseudomonas_aeruginosa/20_deseq2icbi/04_deseq2_batch_effect/volcano_names/genes_of_interest_volcano_dreg.csv --c1=hAO_inf --c2=hAO_ctrl --sample_col=sample --condition_col=group --remove_batch_effect --batch_col=batch --fdr_cutoff=0.1 --fc_cutoff=0.5
 
