input: /home/boeck/myScratch/Pseudomonas/tables/samplesheet.csv
gtf: /data/genomes/hg38/annotation/gencode/gencode.v38.primary_assembly.annotation.gtf
outdir: /home/boeck/myScratch/Pseudomonas/data/RNAseq/10_rnaseq_pipeline
star_index: /data/genomes/hg38/index/STAR/2.7.9a/gencode/gencode.v38.GRCh38.primary_assembly.genome/200/
fasta: /data/genomes/hg38/fasta/gencode/GRCh38.primary_assembly.genome.fa
gencode: true
publish_dir_mode: copy
extra_star_align_args: --alignIntronMax 1000000 --alignIntronMin 20 --alignMatesGapMax 1000000 --alignSJoverhangMin 8 --outFilterMismatchNmax 999 --outFilterType BySJout --outFilterMismatchNoverLmax 0.1 --clip3pAdapterSeq AAAAAAAA
extra_salmon_quant_args: --noLengthCorrection